# Site/SEO settings
email: mocha0913@naver.com
baseurl: ""
permalink: /:year/:month/:day/:title/
google_analytics:

name: KOOO
title: KOOO Portfolio
description: >
  KOOO - a Web Designer's Portfolio
url: https://koooportfolio.github.io
# twitter_username: eungggggg
default_img: /assets/images/illusttt.JPG
social:
  # - name: twitter
  #   url: https://twitter.com/eungggggg
  - name: instagram
    url: https://www.instagram.com/kooo.illust
  #- name: dribbble
  #  url: https://dribbble.com/eungggg
  #- name: behance
  #  url: https://www.behance.net/eungggggg
  #- name: linkedin
  #  url: https://www.linkedin.com/in/eungggggg/
  #- name: github
  #  url: https://github.com/eungggggg
  # - name: codepen
  #   url: https://codepen.io/eungggggg/

# Contact settings
contact_img: /assets/images/placeholder-28.jpg
formcarry: https://formcarry.com/s/HkIo0nMb7

# Disqus settings
disqus: test-apkdzgmqhj

# MailChimp settings
mailchimp_action: https://samesies.us17.list-manage.com/subscribe/post-json?u=66ddf555dab480e6a8606430b&amp;id=89b3ee034f
mailchimp_input: b_66ddf555dab480e6a8606430b_89b3ee034f

# Author settings
author:
  - name: KOOO
    # bio: Thomas Vaeth was born in New York, raised in Pennsylvania, and transplanted in Washington. He was a Web Developer at Urban Influence, but now he's a Software Engineer at Getty Images.
    # url: http://thomasvaeth.com

# Pagination settings
pagination:
  enabled: true
  debug: false
  per_page: 12
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts:
      - 'tag.html'
    title: 'The Barber Theme'
    permalink: '/tag/:tag'
    slugify:
      mode: raw
      cased: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
